name: 
servicesCidrBlock: 10.0.0.0/16
location: eastus
clusterResourceGroup: 
subscriptionId: 0fe1cc35-0cfa-4152-97d7-5dfb45a8d4ba
k8sVersion: v1.19.6
networkPolicy: azure
networkPlugin: kubenet
controlAgentPoolName: clagentpool
controlAgentPoolNodes: 2
controlAgentPoolNodeSize: Standard_D8s_v3
workerAgentPoolName: wragentpool
workerAgentPoolNodes: 1
workerAgentPoolNodeSize: Standard_D8s_v3